"""Added required tables

Revision ID: a4e76dc595a7
Revises: ab98effff81c
Create Date: 2022-07-18 23:28:51.190707

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'a4e76dc595a7'
down_revision = 'ab98effff81c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
